joint_limits:
  shoulder_pan_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: 6.283185307179586
    max_velocity: 3.141592653589793
    min_position: -6.283185307179586
  shoulder_lift_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: 6.283185307179586
    max_velocity: 3.141592653589793
    min_position: -6.283185307179586
  elbow_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: 3.141592653589793
    max_velocity: 3.141592653589793
    min_position: -3.141592653589793
  wrist_1_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: 6.283185307179586
    max_velocity: 3.141592653589793
    min_position: -6.283185307179586
  wrist_2_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: 6.283185307179586
    max_velocity: 3.141592653589793
    min_position: -6.283185307179586
  wrist_3_joint:
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: 6.283185307179586
    max_velocity: 3.141592653589793
    min_position: -6.283185307179586
